# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5793209905cb76d800ec092f03922573dfd30a9f8aab1338c1afbac8e6851bbc20742055dd95c8e4de01d0ab50fd702de9657dbb7633d8d64fc5d8795456cc5

test:
  secret_key_base: c4d74a0781673660fc4eec30bbf519421cdc600ac8f4b055dec26496bd208c04e0addda3fb99d6872004451b963f3da2bba5bba32a24e5ce01be8ad5a5af90a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
